AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template S3_Website_Bucket_With_Retain_On_Delete:
  Template showing how to create a publicly accessible S3 bucket with a deletion policy of retain on delete.
  This template creates an S3 bucket that will NOT be deleted when the stack is deleted.

Parameters:
  BucketNameParam:
    Description: The S3 Bucket Name
    Type: String
  EnvironmentName:
    Description: SDLC Environment Value e.g dev/qa/prod.
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref EnvironmentName, !Ref BucketNameParam ] ]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index1.html
        ErrorDocument: error1.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Retain
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content